using cYo.Common.ComponentModel;
using cYo.Common.Win32;
using cYo.Common.Windows.Forms;
using cYo.Projects.ComicRack.Engine;
using cYo.Projects.ComicRack.Engine.Display;
using cYo.Projects.ComicRack.Viewer.Views;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace cYo.Projects.ComicRack.Viewer;

public partial class MainMenuControl : UserControl
{
    /// <summary>
    /// Required designer variable.
    /// </summary>
    private System.ComponentModel.IContainer components = null;

    //protected override void Dispose(bool disposing)
    //{
    //    if (disposing)
    //    {
    //        IdleProcess.Idle -= Application_Idle;
    //        Program.Database.BookChanged -= WatchedBookHasChanged;
    //        Program.BookFactory.TemporaryBookChanged -= WatchedBookHasChanged;
    //        books.BookOpened -= OnBookOpened;
    //        books.Slots.Changed -= OpenBooks_SlotsChanged;
    //        books.Slots.ForEach(delegate (ComicBookNavigator n)
    //        {
    //            n.SafeDispose();
    //        });
    //        books.Slots.Clear();
    //        Program.Settings.SettingsChanged -= SettingsChanged;
    //        ToolStripStatusLabel toolStripStatusLabel = tsScanActivity;
    //        ToolStripStatusLabel toolStripStatusLabel2 = tsReadInfoActivity;
    //        ToolStripStatusLabel toolStripStatusLabel3 = tsWriteInfoActivity;
    //        ToolStripStatusLabel toolStripStatusLabel4 = tsPageActivity;
    //        bool flag2 = (tsExportActivity.Visible = false);
    //        bool flag4 = (toolStripStatusLabel4.Visible = flag2);
    //        bool flag6 = (toolStripStatusLabel3.Visible = flag4);
    //        bool visible = (toolStripStatusLabel2.Visible = flag6);
    //        toolStripStatusLabel.Visible = visible;
    //        if (comicDisplay != null)
    //        {
    //            comicDisplay.Dispose();
    //        }
    //        if (components != null)
    //        {
    //            components.Dispose();
    //        }
    //    }
    //    base.Dispose(disposing);
    //}

    /// <summary> 
    /// Clean up any resources being used.
    /// </summary>
    /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
  

    }

    private ComicDisplay comicDisplay;
    private readonly NavigatorManager books;
    private Timer mouseDisableTimer;
    private MenuStrip mainMenuStrip;
    private ToolStripMenuItem fileMenu;
    private ToolStripMenuItem miOpenComic;
    private ToolStripSeparator toolStripMenuItem14;
    private ToolStripMenuItem miAddFolderToLibrary;
    private ToolStripMenuItem miScan;
    private ToolStripSeparator toolStripInsertSeperator;
    private ToolStripMenuItem miOpenRecent;
    private ToolStripSeparator toolStripMenuItem4;
    private ToolStripMenuItem miExit;
    private ToolStripMenuItem editMenu;
    private ToolStripMenuItem miShowInfo;
    private ToolStripMenuItem miRating;
    private ToolStripSeparator toolStripSeparator4;
    private ToolStripMenuItem miPreferences;
    private ToolStripMenuItem readMenu;
    private ToolStripMenuItem miFirstPage;
    private ToolStripMenuItem miPrevPage;
    private ToolStripMenuItem miNextPage;
    private ToolStripMenuItem miLastPage;
    private ToolStripSeparator toolStripMenuItem1;
    private ToolStripMenuItem miPrevFromList;
    private ToolStripMenuItem miNextFromList;
    private ToolStripMenuItem displayMenu;
    private ToolStripSeparator toolStripSeparator3;
    private ToolStripSeparator toolStripMenuItem41;
    private ToolStripMenuItem helpMenu;
    private ToolStripMenuItem miWebHome;
    private ToolStripMenuItem miWebUserForum;
    private ToolStripSeparator toolStripMenuItem5;
    private ToolStripMenuItem miAbout;
    private StatusStrip statusStrip;
    private ToolStripStatusLabel tsText;
    private ToolStripStatusLabel tsScanActivity;
    private ToolStripStatusLabel tsBook;
    private ToolStripStatusLabel tsCurrentPage;
    private ToolStripStatusLabel tsPageCount;
    private MainView mainView;
    private ToolStripMenuItem miZoom;
    private ToolStripMenuItem miRotation;
    private ToolStripMenuItem miRotate0;
    private ToolStripMenuItem miRotate90;
    private ToolStripMenuItem miRotate180;
    private ToolStripMenuItem miRotate270;
    private ContextMenuStrip pageContextMenu;
    private ToolStripMenuItem cmShowInfo;
    private ToolStripMenuItem cmRating;
    private ToolStripSeparator toolStripSeparator2;
    private ToolStripMenuItem cmCopyPage;
    private ToolStripSeparator toolStripSeparator10;
    private ToolStripMenuItem cmRefreshPage;
    private NotifyIcon notifyIcon;
    private ToolStripMenuItem miNews;
    private ToolStripMenuItem miMagnify;
    private ToolStripMenuItem cmMagnify;
    private ToolStripMenuItem miFileAutomation;
    private ToolStripSeparator toolStripMenuItem40;
    private ToolStripMenuItem miViewRefresh;
    private ToolStripMenuItem browseMenu;
    private ToolStripMenuItem miViewLibrary;
    private ToolStripMenuItem miViewFolders;
    private ToolStripMenuItem miViewPages;
    private ToolStripSeparator toolStripMenuItem9;
    private ToolStripMenuItem miSidebar;
    private ToolStripMenuItem miSmallPreview;
    private ToolStripMenuItem miSearchBrowser;
    private ToolStripMenuItem miFullScreen;
    private ToolStripMenuItem miToggleBrowser;
    private ToolStripSeparator toolStripMenuItem2;
    private ToolStripStatusLabel tsWriteInfoActivity;
    private ToolStripStatusLabel tsExportActivity;
    private ToolStripMenuItem cmPageType;
    private ToolStripMenuItem miSyncBrowser;
    private SizableContainer mainViewContainer;
    private ToolStripSeparator toolStripMenuItem11;
    private ContextMenuStrip notfifyContextMenu;
    private ToolStripMenuItem cmNotifyRestore;
    private ToolStripSeparator toolStripMenuItem15;
    private ToolStripMenuItem cmNotifyExit;
    private TabBar fileTabs;
    private ToolStripMenuItem miCloseComic;
    private ToolStripMenuItem miCloseAllComics;
    private ToolStripSeparator toolStripMenuItem7;
    private ToolStripMenuItem miAddTab;
    private Panel viewContainer;
    private ToolStripMenuItem miOpenNow;
    private ToolStripSeparator toolStripMenuItem17;
    private ToolStripMenuItem miPrevTab;
    private ToolStripMenuItem miNextTab;
    private ToolStripStatusLabel tsPageActivity;
    private ToolStripMenuItem cmExportPage;
    private ToolStripSeparator toolStripMenuItem6;
    private ToolStripMenuItem miListLayouts;
    private ToolStripMenuItem miEditListLayout;
    private ToolStripMenuItem miSaveListLayout;
    private ToolStripMenuItem miEditLayouts;
    private ToolStripMenuItem miSetAllListsSame;
    private ToolStripSeparator miLayoutSep;
    private ToolStripMenuItem cmPageLayout;
    private ToolStripMenuItem cmFitAll;
    private ToolStripMenuItem cmFitWidth;
    private ToolStripMenuItem cmFitHeight;
    private ToolStripMenuItem cmFitBest;
    private ToolStripMenuItem miRestart;
    private ToolStripSeparator toolStripMenuItem24;
    private ToolStripSeparator toolStripMenuItem25;
    private ToolStripMenuItem miReaderUndocked;
    private Panel panelReader;
    private Panel readerContainer;
    private ToolStripMenuItem miPageLayout;
    private ToolStripMenuItem miFitAll;
    private ToolStripMenuItem miFitWidth;
    private ToolStripMenuItem miFitHeight;
    private ToolStripMenuItem miBestFit;
    private ToolStripSeparator toolStripMenuItem29;
    private ToolStripMenuItem miWorkspaces;
    private ToolStripMenuItem miSaveWorkspace;
    private ToolStripMenuItem miEditWorkspaces;
    private ToolStripSeparator miWorkspaceSep;
    private ToolStripMenuItem miOriginal;
    private ToolStripMenuItem cmOriginal;
    private ToolStripMenuItem cmFitWidthAdaptive;
    private ToolStripMenuItem miFitWidthAdaptive;
    private ToolStripMenuItem miOnlyFitOversized;
    private ToolStripMenuItem cmOnlyFitOversized;
    private ToolStripMenuItem miAutoScroll;
    private ToolStripMenuItem miRightToLeft;
    private ToolStripMenuItem miDoublePageAutoScroll;
    private ToolStripMenuItem cmRightToLeft;
    private ToolStripSeparator toolStripMenuItem27;
    private ToolStripMenuItem miMinimalGui;
    private ToolStripMenuItem cmMinimalGui;
    private ToolStripMenuItem miWebHelp;
    private ToolStripSeparator toolStripMenuItem3;
    private ToolStripSeparator toolStripMenuItem18;
    private ToolStripMenuItem cmBookmarks;
    private ToolStripMenuItem cmSetBookmark;
    private ToolStripMenuItem cmRemoveBookmark;
    private ToolStripSeparator toolStripSeparator13;
    private ToolStripMenuItem cmLastPageRead;
    private ToolStripSeparator toolStripMenuItem23;
    private ToolStripSeparator toolStripMenuItem32;
    private ToolStripMenuItem cmPrevBookmark;
    private ToolStripMenuItem cmNextBookmark;
    private ToolStripMenuItem miZoomIn;
    private ToolStripMenuItem miZoomOut;
    private ToolStripSeparator toolStripSeparator14;
    private ToolStripMenuItem miZoom100;
    private ToolStripMenuItem miZoom125;
    private ToolStripMenuItem miZoom150;
    private ToolStripMenuItem miZoom200;
    private ToolStripMenuItem miZoom400;
    private ToolStripSeparator toolStripSeparator15;
    private ToolStripMenuItem miZoomCustom;
    private ToolStripMenuItem miRotateLeft;
    private ToolStripMenuItem miRotateRight;
    private ToolStripSeparator toolStripMenuItem33;
    private ToolStripSeparator toolStripMenuItem36;
    private ToolStripMenuItem miAutoRotate;
    private ContextMenuStrip tabContextMenu;
    private ToolStripMenuItem cmClose;
    private ToolStripMenuItem cmCloseAllButThis;
    private ToolStripSeparator toolStripMenuItem35;
    private ToolStripMenuItem cmCopyPath;
    private ToolStripMenuItem cmRevealInExplorer;
    private ToolStripMenuItem cmSyncBrowser;
    private ToolStripMenuItem miTasks;
    private ToolStripStatusLabel tsReadInfoActivity;
    private ToolStripSeparator toolStripMenuItem22;
    private ToolStripMenuItem miPageType;
    private ToolStripMenuItem miBookmarks;
    private ToolStripMenuItem miSetBookmark;
    private ToolStripMenuItem miRemoveBookmark;
    private ToolStripSeparator toolStripMenuItem26;
    private ToolStripMenuItem miPrevBookmark;
    private ToolStripMenuItem miNextBookmark;
    private ToolStripSeparator toolStripMenuItem8;
    private ToolStripMenuItem miLastPageRead;
    private ToolStripMenuItem miCopyPage;
    private ToolStripMenuItem miExportPage;
    private ToolStripSeparator toolStripMenuItem39;
    private ToolStripSeparator sepBeforeRevealInBrowser;
    private ToolStripMenuItem cmComics;
    private ToolStripMenuItem cmOpenComic;
    private ToolStripMenuItem cmCloseComic;
    private ToolStripSeparator toolStripMenuItem13;
    private ToolStripMenuItem cmPrevFromList;
    private ToolStripMenuItem cmNextFromList;
    private ToolStripMenuItem cmPageRotate;
    private ToolStripSeparator toolStripMenuItem38;
    private ToolStripMenuItem cmRotate0;
    private ToolStripMenuItem cmRotate90;
    private ToolStripMenuItem cmRotate180;
    private ToolStripMenuItem cmRotate270;
    private ToolStripMenuItem miPageRotate;
    private ToolStripSeparator toolStripMenuItem42;
    private ToolStripMenuItem miOpenRemoteLibrary;
    private ToolStripMenuItem miRandomFromList;
    private ToolStripMenuItem cmRandomFromList;
    private ToolStripMenuItem miUpdateAllComicFiles;
    private ToolStripSeparator toolStripMenuItem43;
    private ToolStripMenuItem miUndo;
    private ToolStripMenuItem miRedo;
    private Timer trimTimer;
    private ToolStripSeparator toolStripMenuItem44;
    private ToolStripMenuItem miComicDisplaySettings;
    private ToolStrip mainToolStrip;
    private ToolStripSplitButton tbFit;
    private ToolStripMenuItem tbOriginal;
    private ToolStripMenuItem tbFitAll;
    private ToolStripMenuItem tbFitWidth;
    private ToolStripMenuItem tbFitWidthAdaptive;
    private ToolStripMenuItem tbFitHeight;
    private ToolStripMenuItem tbBestFit;
    private ToolStripSeparator toolStripMenuItem20;
    private ToolStripMenuItem tbOnlyFitOversized;
    private ToolStripSplitButton tbZoom;
    private ToolStripMenuItem tbZoomIn;
    private ToolStripMenuItem tbZoomOut;
    private ToolStripSeparator toolStripMenuItem30;
    private ToolStripMenuItem tbZoom100;
    private ToolStripMenuItem tbZoom125;
    private ToolStripMenuItem tbZoom150;
    private ToolStripMenuItem tbZoom200;
    private ToolStripMenuItem tbZoom400;
    private ToolStripSeparator toolStripMenuItem31;
    private ToolStripMenuItem tbZoomCustom;
    private ToolStripSplitButton tbRotate;
    private ToolStripMenuItem tbRotateLeft;
    private ToolStripMenuItem tbRotateRight;
    private ToolStripSeparator toolStripSeparator11;
    private ToolStripMenuItem tbRotate0;
    private ToolStripMenuItem tbRotate90;
    private ToolStripMenuItem tbRotate180;
    private ToolStripMenuItem tbRotate270;
    private ToolStripSeparator toolStripMenuItem34;
    private ToolStripMenuItem tbAutoRotate;
    private ToolStripSeparator toolStripSeparator7;
    private ToolStripSplitButton tbMagnify;
    private ToolStripSeparator toolStripSeparator1;
    private ToolStripDropDownButton tbTools;
    private ToolStripSeparator toolStripSeparator5;
    private ToolStripSplitButton tbPrevPage;
    private ToolStripMenuItem tbFirstPage;
    private ToolStripMenuItem tbPrevFromList;
    private ToolStripSplitButton tbNextPage;
    private ToolStripMenuItem tbLastPage;
    private ToolStripMenuItem tbNextFromList;
    private ToolStripSeparator toolStripMenuItem49;
    private ToolStripMenuItem tbRandomFromList;
    private ContextMenuStrip toolsContextMenu;
    private ToolStripMenuItem tbOpenComic;
    private ToolStripMenuItem tbShowInfo;
    private ToolStripSeparator toolStripMenuItem47;
    private ToolStripMenuItem tsWorkspaces;
    private ToolStripMenuItem tsSaveWorkspace;
    private ToolStripMenuItem tsEditWorkspaces;
    private ToolStripSeparator tsWorkspaceSep;
    private ToolStripMenuItem tbBookmarks;
    private ToolStripMenuItem tbSetBookmark;
    private ToolStripMenuItem tbRemoveBookmark;
    private ToolStripSeparator tbBookmarkSeparator;
    private ToolStripMenuItem tbAutoScroll;
    private ToolStripSeparator toolStripMenuItem45;
    private ToolStripMenuItem tbMinimalGui;
    private ToolStripMenuItem tbReaderUndocked;
    private ToolStripSeparator toolStripMenuItem52;
    private ToolStripMenuItem tbScan;
    private ToolStripMenuItem tbUpdateAllComicFiles;
    private ToolStripSeparator toolStripMenuItem48;
    private ToolStripMenuItem tbComicDisplaySettings;
    private ToolStripMenuItem tbPreferences;
    private ToolStripMenuItem tbAbout;
    private ToolStripSeparator toolStripMenuItem50;
    private ToolStripMenuItem tbShowMainMenu;
    private ToolStripSeparator toolStripMenuItem51;
    private ToolStripMenuItem tbExit;
    private ToolStripSeparator toolStripMenuItem46;
    private ToolStripMenuItem tbPrevBookmark;
    private ToolStripSeparator toolStripMenuItem19;
    private ToolStripMenuItem tbNextBookmark;
    private ToolStripMenuItem tbLastPageRead;
    private ToolStripSeparator cmBookmarkSeparator;
    private ToolStripSeparator toolStripMenuItem28;
    private ToolStripSeparator toolStripMenuItem53;
    private Timer updateActivityTimer;
    private ToolStripSplitButton tbPageLayout;
    private ToolStripMenuItem tbTwoPagesAdaptive;
    private ToolStripMenuItem tbSinglePage;
    private ToolStripMenuItem tbTwoPages;
    private ToolStripSeparator toolStripMenuItem54;
    private ToolStripMenuItem tbRightToLeft;
    private ToolStripMenuItem miTwoPagesAdaptive;
    private ToolStripMenuItem miTwoPages;
    private ToolStripMenuItem miSinglePage;
    private ToolStripMenuItem cmSinglePage;
    private ToolStripMenuItem cmTwoPages;
    private ToolStripMenuItem cmTwoPagesAdaptive;
    private ToolStripSeparator toolStripMenuItem55;
    private ToolStripSeparator toolStripMenuItem56;
    private ToolStripMenuItem miPreviousList;
    private ToolStripMenuItem miNextList;
    private ToolStripMenuItem miUpdateWebComics;
    private ToolStripMenuItem tbUpdateWebComics;
    private ToolStripMenuItem tbOpenRemoteLibrary;
    private ToolStripMenuItem miInfoPanel;
    private ToolStripStatusLabel tsServerActivity;
    private ToolStripSeparator toolStripMenuItem37;
    private ToolStripMenuItem miNewComic;
    private ToolStripMenuItem miToggleZoom;
    private ToolStripSeparator toolStripMenuItem57;
    private ToolStripSeparator toolStripMenuItem10;
    private QuickOpenView quickOpenView;
    private ToolStripButton tbFullScreen;
    private ContextMenuStrip contextRating;
    private ToolStripMenuItem miRate0;
    private ToolStripSeparator toolStripMenuItem12;
    private ToolStripMenuItem miRate1;
    private ToolStripMenuItem miRate2;
    private ToolStripMenuItem miRate3;
    private ToolStripMenuItem miRate4;
    private ToolStripMenuItem miRate5;
    private ContextMenuStrip contextRating2;
    private ToolStripMenuItem cmRate0;
    private ToolStripSeparator toolStripMenuItem16;
    private ToolStripMenuItem cmRate1;
    private ToolStripMenuItem cmRate2;
    private ToolStripMenuItem cmRate3;
    private ToolStripMenuItem cmRate4;
    private ToolStripMenuItem cmRate5;
    private ToolStripMenuItem cmCloseAllToTheRight;
    private ToolStripSeparator cmComicsSep;
    private ToolStripMenuItem miHelp;
    private ToolStripMenuItem miChooseHelpSystem;
    private ToolStripMenuItem miHelpPlugins;
    private ToolStripMenuItem miHelpQuickIntro;
    private ToolStripMenuItem miDevices;
    private ToolStripMenuItem miSynchronizeDevices;
    private ToolStripStatusLabel tsDeviceSyncActivity;
    private ToolStripMenuItem tsSynchronizeDevices;
    private ToolStripSeparator toolStripMenuItem21;
    private ToolStripMenuItem miTrackCurrentPage;
    private ToolStripStatusLabel tsDataSourceState;
    private ToolStripSeparator toolStripMenuItem58;
    private ToolStripMenuItem miQuickRating;
    private ToolStripSeparator toolStripSeparator6;
    private ToolStripMenuItem cmQuickRating;
    private ToolStripMenuItem miCheckUpdate;
    private ToolStripMenuItem miCacheThumbnails;
    private ToolStripMenuItem tbCacheThumbnails;
}
